### ISSUE TITLE
config.CustomizeYaml: Unsecure usage of yaml.load()

### ISSUE THREAD

**Issue by frlan** [flyingcircusio/batou_ext#30]
A deployment using CustomizeYaml giving this warning:

```
/deployment/.batou/3537682d/lib/python3.7/site-packages/batou_ext/config.py:96: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f)
```

**Comment by frlan** [comment]
requirements.txt: 
```
pyaml==17.12.1
batou_ext @ https://github.com/flyingcircusio/batou_ext/archive/32671735466f2d596eaf41d2f74bb04faeaf20da.zip#sha256=5a1cbe7c62af3074d8587f45fd3594ded6f351ea105b2e9ba9af8e06fd3f0d4b
batou==2.0
```

**Comment by nichmoe** [comment]
Calling CustomizeYaml() now fails completely.
```
ERROR: Traceback (most recent call last):
  File "/Users/user/project-batou/.appenv/e2170168/lib/python3.9/site-packages/batou/remote_core.py", line 390, in <module>
  File "/Users/user/project-batou/.appenv/e2170168/lib/python3.9/site-packages/batou/remote_core.py", line 350, in deploy
  File "/Users/user/project-batou/.appenv/e2170168/lib/python3.9/site-packages/batou/remote_core.py", line 171, in deploy
  File "/srv/s-dev/deployment/.appenv/04955068/lib/python3.8/site-packages/batou/component.py", line 323, in deploy
    sub_component.deploy(predict_only)
  File "/srv/s-dev/deployment/.appenv/04955068/lib/python3.8/site-packages/batou/component.py", line 335, in deploy
    call_with_optional_args(
  File "/srv/s-dev/deployment/.appenv/04955068/lib/python3.8/site-packages/batou/utils.py", line 471, in call_with_optional_args
    return func(**call_kw)
  File "/srv/s-dev/deployment/.appenv/04955068/lib/python3.8/site-packages/batou_ext/config.py", line 103, in verify
    self._config = self._generate()
  File "/srv/s-dev/deployment/.appenv/04955068/lib/python3.8/site-packages/batou_ext/config.py", line 97, in _generate
    data = yaml.load(f)
TypeError: load() missing 1 required positional argument: 'Loader'
```
requirenments.txt
```
pyaml==21.10.1
batou>=2.3b3
batou_ext @ https://github.com/flyingcircusio/batou_ext/archive/a875a4f7cfe8d53e56930f7c579b9430d8670cff.zip#sha256=48d44fb85315bfa61132e987daf0dcc4f4a118054357df451e9bb0d605a2ef12
```
